import type { AdmissionApplicationRow, AdmissionFormValues } from "@/types";

// ============================================================
// Operations ▸ Admission service.
//
// Rows are hard-coded for this phase: the page renders the real
// admission form (every column of `admissionapplication`) while the
// backend list/create routes are still only used by the public apply
// form. Swap the body of `getAdmissionApplications` for
// `api.get<AdmissionApplicationRow[]>("/admissions/applications")`
// once those routes exist.
// ============================================================

/** Every form field, blank — seeds spread this and override what's filled. */
export function blankAdmissionForm(): AdmissionFormValues {
    return {
        studentFirstName: "",
        studentMiddleName: "",
        studentLastName: "",
        dateOfBirth: "",
        gender: "",
        bloodGroup: "",
        religion: "",
        category: "",
        motherTongue: "",
        nationality: "",
        aadhaarId: "",
        address: "",
        permanentAddress: "",
        previousSchoolName: "",
        previousClassPassed: "",
        previousBoard: "",
        transferCertificateNo: "",
        oldUniqueId: "",
        fatherName: "",
        fatherOccupation: "",
        fatherPhone: "",
        fatherEmail: "",
        fatherAnnualIncome: "",
        motherName: "",
        motherOccupation: "",
        motherPhone: "",
        motherEmail: "",
        motherAnnualIncome: "",
        guardianName: "",
        guardianRelation: "",
        guardianPhone: "",
        guardianEmail: "",
        guardianOccupation: "",
        guardianAddress: "",
        appliedForClassLevel: "",
        currentClassOrLastClass: "",
        appliedSectionPreference: "",
        needsTransport: "",
        transportRoute: "",
        needsHostel: "",
        notes: "",
    };
}

const APPLICATIONS: AdmissionApplicationRow[] = [
    {
        ...blankAdmissionForm(),
        id: 1,
        applicationNo: "ADM-2026-0141",
        status: "Registered",
        createdOn: "2026-09-18",
        studentFirstName: "Aarav",
        studentLastName: "Sharma",
        dateOfBirth: "2014-06-12",
        gender: "Male",
        bloodGroup: "B+",
        category: "General",
        nationality: "Indian",
        address: "12 Rose Villa, Kothrud, Pune 411038",
        fatherName: "Rakesh Sharma",
        fatherOccupation: "Engineer",
        fatherPhone: "+91 98200 11223",
        fatherEmail: "rakesh.sharma@example.com",
        motherName: "Sunita Sharma",
        motherPhone: "+91 98200 11224",
        appliedForClassLevel: "Class 6",
        currentClassOrLastClass: "Class 6",
        appliedSectionPreference: "A",
        needsTransport: "Yes",
        transportRoute: "Route 4 — Kothrud",
        previousSchoolName: "Sunrise Public School",
    },
    {
        ...blankAdmissionForm(),
        id: 2,
        applicationNo: "ADM-2026-0142",
        status: "Registered",
        createdOn: "2026-09-19",
        studentFirstName: "Diya",
        studentLastName: "Nair",
        dateOfBirth: "2012-11-02",
        gender: "Female",
        category: "OBC",
        nationality: "Indian",
        address: "44 Palm Grove, Aundh, Pune 411007",
        fatherName: "Suresh Nair",
        fatherPhone: "+91 98200 44556",
        fatherEmail: "suresh.nair@example.com",
        motherName: "Meera Nair",
        motherEmail: "meera.nair@example.com",
        appliedForClassLevel: "Class 8",
        currentClassOrLastClass: "Class 8",
        appliedSectionPreference: "B",
        previousSchoolName: "St. Xavier's High School",
        previousClassPassed: "Class 7",
    },
    {
        ...blankAdmissionForm(),
        id: 3,
        applicationNo: "ADM-2026-0143",
        status: "Registered",
        createdOn: "2026-09-21",
        studentFirstName: "Kabir",
        studentLastName: "Verma",
        dateOfBirth: "2011-03-27",
        gender: "Male",
        nationality: "Indian",
        address: "7 Lake View, Baner, Pune 411045",
        fatherName: "Anil Verma",
        fatherPhone: "+91 98200 77889",
        guardianName: "Shalini Verma",
        guardianRelation: "Aunt",
        guardianPhone: "+91 98200 77890",
        appliedForClassLevel: "Class 9",
        currentClassOrLastClass: "Class 9",
        appliedSectionPreference: "A",
        needsHostel: "No",
        separation: {
            droppedClass: "Class 9",
            reason: "Rusticated",
            session: "Incomplete Session",
            date: "2026-09-30",
        },
    },
    {
        ...blankAdmissionForm(),
        id: 4,
        applicationNo: "ADM-2026-0144",
        status: "Registered",
        createdOn: "2026-09-25",
        studentFirstName: "Anaya",
        studentLastName: "Iyer",
        dateOfBirth: "2010-08-09",
        gender: "Female",
        nationality: "Indian",
        address: "21 Hill Road, Shivaji Nagar, Pune 411005",
        fatherName: "Kiran Iyer",
        fatherPhone: "+91 98200 66554",
        fatherEmail: "kiran.iyer@example.com",
        motherName: "Lakshmi Iyer",
        motherPhone: "+91 98200 66555",
        appliedForClassLevel: "Class 10",
        currentClassOrLastClass: "Class 10",
        appliedSectionPreference: "C",
        separation: {
            droppedClass: "Class 10",
            reason: "Transfer Certificate Issued",
            session: "Completed Session",
            date: "2026-09-27",
        },
    },
    {
        ...blankAdmissionForm(),
        id: 5,
        applicationNo: "ADM-2026-0145",
        status: "Draft",
        createdOn: "2026-09-24",
        studentFirstName: "Vihaan",
        studentLastName: "Gupta",
        gender: "Male",
        appliedForClassLevel: "Class 11",
        currentClassOrLastClass: "Class 11",
        appliedSectionPreference: "A",
        guardianName: "Neha Gupta",
        guardianPhone: "+91 98200 99110",
    },
    {
        ...blankAdmissionForm(),
        id: 6,
        applicationNo: "ADM-2026-0146",
        status: "Draft",
        createdOn: "2026-09-26",
        studentFirstName: "Ishita",
        studentLastName: "Rao",
        dateOfBirth: "2013-01-30",
        gender: "Female",
        appliedForClassLevel: "Class 7",
        currentClassOrLastClass: "Class 7",
        fatherName: "Suresh Rao",
        fatherPhone: "+91 98200 33445",
    },
    {
        ...blankAdmissionForm(),
        id: 7,
        applicationNo: "ADM-2026-0147",
        status: "Draft",
        createdOn: "2026-09-28",
        studentFirstName: "Reyansh",
        studentLastName: "Patil",
        appliedForClassLevel: "Class 6",
        currentClassOrLastClass: "Class 6",
        needsTransport: "Yes",
    },
];

export async function getAdmissionApplications(): Promise<AdmissionApplicationRow[]> {
    return APPLICATIONS;
}

