"""Initial setup

Revision ID: 8a84d5ed6a1f
Revises: 8688cdb7b555
Create Date: 2026-09-03 12:23:32.400176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8a84d5ed6a1f'
down_revision: Union[str, Sequence[str], None] = '8688cdb7b555'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admissionapplication',
    sa.Column('student_first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('student_last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('guardian_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('guardian_email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('guardian_phone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('applied_for_class_level', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'under_review', 'approved', 'rejected', name='admissionstatus'), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chatthread',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_group', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gradeclass',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gradeclass_name'), 'gradeclass', ['name'], unique=True)
    op.create_table('subject',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subject_code'), 'subject', ['code'], unique=True)
    op.create_index(op.f('ix_subject_name'), 'subject', ['name'], unique=True)
    op.create_table('chatmessage',
    sa.Column('thread_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('content_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('attachment_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['thread_id'], ['chatthread.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chatthreadparticipant',
    sa.Column('thread_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['thread_id'], ['chatthread.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('thread_id', 'user_id')
    )
    op.create_table('examterm',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('grade_class_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['grade_class_id'], ['gradeclass.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feestructure',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('grade_class_id', sa.Integer(), nullable=False),
    sa.Column('frequency', sa.Enum('monthly', 'term', 'yearly', 'one_time', name='feefrequency'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['grade_class_id'], ['gradeclass.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('section',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('grade_class_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['grade_class_id'], ['gradeclass.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teacherprofile',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('department', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('qualification', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('joining_date', sa.Date(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('exampaper',
    sa.Column('exam_term_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'in_review', 'approved', name='exampaperstatus'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['exam_term_id'], ['examterm.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('homeworkassignment',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('grade_class_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['grade_class_id'], ['gradeclass.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['section.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacherprofile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('studentprofile',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('admission_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('guardian_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('grade_class_id', sa.Integer(), nullable=True),
    sa.Column('section_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['grade_class_id'], ['gradeclass.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['section.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_studentprofile_admission_number'), 'studentprofile', ['admission_number'], unique=True)
    op.create_table('timetableperiod',
    sa.Column('grade_class_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Enum('monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday', name='dayofweek'), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('room', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['grade_class_id'], ['gradeclass.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['section.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacherprofile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attendancerecord',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('grade_class_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('present', 'absent', 'leave', 'late', 'half_day', name='attendancestatus'), nullable=False),
    sa.Column('remarks', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['grade_class_id'], ['gradeclass.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['section.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['studentprofile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('classdiary',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['studentprofile.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacherprofile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('examresult',
    sa.Column('exam_paper_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('marks_obtained', sa.Float(), nullable=False),
    sa.Column('ai_feedback', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exam_paper_id'], ['exampaper.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['studentprofile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feetransaction',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('fee_structure_id', sa.Integer(), nullable=False),
    sa.Column('amount_paid', sa.Float(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('payment_mode', sa.Enum('cash', 'upi', 'card', 'cheque', 'bank_transfer', name='paymentmode'), nullable=False),
    sa.Column('receipt_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fee_structure_id'], ['feestructure.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['studentprofile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feetransaction_receipt_number'), 'feetransaction', ['receipt_number'], unique=True)
    op.create_table('homeworksubmission',
    sa.Column('homework_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('content_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'submitted', 'graded', name='submissionstatus'), nullable=False),
    sa.Column('teacher_feedback', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['homework_id'], ['homeworkassignment.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['studentprofile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('homeworksubmission')
    op.drop_index(op.f('ix_feetransaction_receipt_number'), table_name='feetransaction')
    op.drop_table('feetransaction')
    op.drop_table('examresult')
    op.drop_table('classdiary')
    op.drop_table('attendancerecord')
    op.drop_table('timetableperiod')
    op.drop_index(op.f('ix_studentprofile_admission_number'), table_name='studentprofile')
    op.drop_table('studentprofile')
    op.drop_table('homeworkassignment')
    op.drop_table('exampaper')
    op.drop_table('teacherprofile')
    op.drop_table('section')
    op.drop_table('feestructure')
    op.drop_table('examterm')
    op.drop_table('chatthreadparticipant')
    op.drop_table('chatmessage')
    op.drop_index(op.f('ix_subject_name'), table_name='subject')
    op.drop_index(op.f('ix_subject_code'), table_name='subject')
    op.drop_table('subject')
    op.drop_index(op.f('ix_gradeclass_name'), table_name='gradeclass')
    op.drop_table('gradeclass')
    op.drop_table('chatthread')
    op.drop_table('admissionapplication')
    # ### end Alembic commands ###
