"""Add AttendanceAuditLog

Revision ID: e08a27be1a21
Revises: 8a84d5ed6a1f
Create Date: 2026-09-08 15:07:04.372767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e08a27be1a21'
down_revision: Union[str, Sequence[str], None] = '8a84d5ed6a1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classteacherassignment',
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('grade_class_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['grade_class_id'], ['gradeclass.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['section.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacherprofile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teacherassignment',
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('grade_class_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['grade_class_id'], ['gradeclass.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['section.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacherprofile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('studentparentrelationship',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('parent_user_id', sa.Integer(), nullable=False),
    sa.Column('relationship_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parent_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['studentprofile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attendanceauditlog',
    sa.Column('attendance_record_id', sa.Integer(), nullable=False),
    sa.Column('changed_by_id', sa.Integer(), nullable=False),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.Column('previous_status', postgresql.ENUM('present', 'absent', 'leave', 'late', 'half_day', name='attendancestatus', create_type=False), nullable=True),
    sa.Column('new_status', postgresql.ENUM('present', 'absent', 'leave', 'late', 'half_day', name='attendancestatus', create_type=False), nullable=False),
    sa.Column('previous_remarks', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('new_remarks', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['attendance_record_id'], ['attendancerecord.id'], ),
    sa.ForeignKeyConstraint(['changed_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('attendancerecord', sa.Column('subject_id', sa.Integer(), nullable=True))
    op.add_column('attendancerecord', sa.Column('overridden_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'attendancerecord', 'user', ['overridden_by_id'], ['id'])
    op.create_foreign_key(None, 'attendancerecord', 'subject', ['subject_id'], ['id'])
    resultstatus_enum = postgresql.ENUM('entered', 'approved', 'published', name='resultstatus')
    resultstatus_enum.create(op.get_bind())
    op.add_column('examresult', sa.Column('status', resultstatus_enum, nullable=False))
    op.add_column('examresult', sa.Column('entered_by_id', sa.Integer(), nullable=True))
    op.add_column('examresult', sa.Column('approved_by_id', sa.Integer(), nullable=True))
    op.add_column('examresult', sa.Column('published_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'examresult', 'user', ['published_by_id'], ['id'])
    op.create_foreign_key(None, 'examresult', 'user', ['entered_by_id'], ['id'])
    op.create_foreign_key(None, 'examresult', 'user', ['approved_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'examresult', type_='foreignkey')
    op.drop_constraint(None, 'examresult', type_='foreignkey')
    op.drop_constraint(None, 'examresult', type_='foreignkey')
    op.drop_column('examresult', 'published_by_id')
    op.drop_column('examresult', 'approved_by_id')
    op.drop_column('examresult', 'entered_by_id')
    op.drop_column('examresult', 'status')
    op.drop_constraint(None, 'attendancerecord', type_='foreignkey')
    op.drop_constraint(None, 'attendancerecord', type_='foreignkey')
    op.drop_column('attendancerecord', 'overridden_by_id')
    op.drop_column('attendancerecord', 'subject_id')
    op.drop_table('attendanceauditlog')
    op.drop_table('studentparentrelationship')
    op.drop_table('teacherassignment')
    op.drop_table('classteacherassignment')
    # ### end Alembic commands ###
